[workspace]
resolver = "2"
members = [
  "askama",
  "async-std",
  "aws-lambda",
  "aws-lambda-example",
  "client",
  "conn-id",
  "cookies",
  "example",
  "forwarding",
  "handlebars",
  "head",
  "http",
  "logger",
  "method-override",
  "native-tls",
  "proxy",
  "router",
  "rustls",
  "server-common",
  "sessions",
  "smol",
  "static",
  "static-compiled",
  "tera",
  "testing",
  "tls-common",
  "tokio",
  "trillium",
  "websockets",
]
exclude = ["controllers", "basic-auth"]

[patch.crates-io.trillium-http-types]
git = "https://github.com/trillium-rs/trillium-http-types"
branch = "trillium"
