[package]
name = "trillium-smol"
version = "0.1.2"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "smol runtime adapter for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
async-fs = "1.5.0"
async-global-executor = "2.0.2"
async-io = "1.4.1"
async-net = "1.6.0"
futures-lite = "1.12.0"
log = "0.4.14"
trillium = { path = "../trillium", version = "^0.1.0" }
trillium-http = { path = "../http", version = "^0.1.0" }
trillium-server-common = { path = "../server-common", version = "^0.1.0" }

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.9"
signal-hook-async-std = "0.2.1"

[dev-dependencies]
env_logger = "0.8.4"
trillium-client = { path = "../client" }
trillium-logger = { path = "../logger" }
trillium-testing = { path = "../testing" }
